version: '3.8'
services:
  redis:
    image: redis:7
    ports: ['6379:6379']
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes: ['.:/app']
    ports: ['8000:8000']
    depends_on: ['redis']
    environment:
      - REDIS_DSN=redis://redis:6379
  worker:
    build: .
    command: arq tasks --redis redis://redis:6379
    volumes: ['.:/app']
    depends_on: ['redis', 'web']
    environment:
      - REDIS_DSN=redis://redis:6379